# Site settings
title: Sam Pedley
email: sam@sampedley.com
description: "Hi, I'm a web developer in Chicago."
baseurl: ""
url: "http://sampedley.com"
twitter_username: mrpeds
github_username:  sampedley
include: ['.htaccess']
keywords: sam pedley chicago web developer

# Build settings
markdown: kramdown
permalink: /:title/
highlighter: rouge
sass:
  sass_dir: assets/_sass
  style: compressed

#Site Variables
image: /public/img/booger.jpg

# Nav Bar Data
nav:
- name: Home
  url: /
- name: About
  url: /about
- name: Articles
  url: /articles
